---
# tasks file for ansible-phpipam
- include_tasks: set_facts.yml

- include_tasks: upgrade.yml
  when: >
    phpipam_upgrade or
    phpipam_install_from_git

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: cron.yml
  tags:
    - config_cron

- include_tasks: config_apache2.yml
  tags:
    - config_apache2
  when:
    - phpipam_prettify_links is defined
    - phpipam_prettify_links

- include_tasks: config_phpipam.yml
  tags:
    - config_phpipam

- include_tasks: backups.yml
  tags:
    - phpipam_db_backups
  when:
    - phpipam_enable_db_backups is defined
    - phpipam_enable_db_backups
